name: pokemon
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  flutter_bounceable: ^1.1.0
  flutter_contacts: ^1.1.7+1
  flutter_launcher_icons: ^0.13.1
  flutter_snake_navigationbar: ^0.6.1
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  loading_indicator: ^3.1.0
  toast:
    git:
      url: https://github.com/thomasfranke/flutter_package_toast.git
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

